name: Trigger auto deployment for booking-auth-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/booking-auth-service-AutoDeployTrigger-167b907b-dae6-45f6-8a2e-3da669702536.yml'

  # Allow manual trigger 
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC (azure/login federated token)
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.BOOKINGAUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKINGAUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKINGAUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.BOOKINGAUTHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKINGAUTHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: booking-auth-service
          resourceGroup: booking-rg
          imageToBuild: maneth2000/booking-auth-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


